baseURL = "http://www.gopper.cn/"
languageCode = "zh-cn"
title = "绿蜂巢 GOPPER.CN | SAAS Stacks"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "关于"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "服务"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "技能"
    URL = "team-skills"
    weight = 4    

    [[menu.nav]]
    name = "案例"
    URL = "portfolio"
    weight = 5

    [[menu.nav]]
    name = "联系"
    URL = "contact-us"
    weight = 6

# Site params
[params]
home= "首页"
logo = "images/logo.png"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-genius"
    heading = "构建智慧生态体系"
    content= "绿蜂巢 GOPPER.CN 依托 云计算 | AI 等新型技术和创新型的经济模式，通过解决碎片化系统中的互操作性、信任和透明性问题，助力中小企业实现新业务流程和持续改进现有业务流程，从而实现战略业务目标"
    btn = true
    btnText="我们的服务"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "致力于打造基于中小企业的新型商业生态体系"
    content = "通过优质服务和样板工程，积极拓展潜在的客户，目前已经与数家国内外知名企业及上市公司保持良好、密切的合作。同时，我们也愿意帮助国内众多中小企业，以最便捷最低成本的方式引入数字化技术。"
    btnURL = "#contact-us"
    btnText = "展开合作"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "客户满意"
        icon = "tf-ion-android-happy"
        count = "20+"

        [[params.counter.counterItem]]
        title = "项目完成"
        icon = "tf-ion-archive"
        count = "30+"

        [[params.counter.counterItem]]
        title = "正反馈"
        icon = "tf-ion-thumbsup"
        count = "20+"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "20+"
    
    # footer
    [params.footer]
        copyright = "Gopper.cn"
        copyrightURL = "http://www.gopper.cn"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://github.com/gopperin"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"