baseURL = "http://www.gopper.cn/"
languageCode = "zh-cn"
title = "北京绿蜂巢网络 GOPPER.CN | SAAS Stacks"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "关于"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "服务"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "技能"
    URL = "team-skills"
    weight = 4    

    [[menu.nav]]
    name = "案例"
    URL = "portfolio"
    weight = 5

    [[menu.nav]]
    name = "联系"
    URL = "contact-us"
    weight = 6

# Site params
[params]
home= "首页"
logo = "images/logo.png"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-genius"
    heading = "构建中小企业应用软件"
    content= "北京绿蜂巢网络 GOPPER.CN 依托技术解决系统碎片化问题，助力中小企业实现新业务流程和持续改进"
    btn = true
    btnText="我们的服务"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "致力于打造适用于中小企业的技术体系"
    content = "灵活、敏捷、快速"
    btnURL = "#contact-us"
    btnText = "展开合作"

    # footer
    [params.footer]
        copyright = "Gopper.cn"
        copyrightURL = "http://www.gopper.cn"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://github.com/gopperin"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"